
#spring的配置
spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.49.181:3306/bjsxt-his?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: root

    #注入的数据源的类型，默认是HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      min-idle: 5
      validation-query: select x
      initial-size: 3
      max-wait: 5000
      stat-view-servlet:
        #监控页面登录账号和密码
        #        login-username: root
        #        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
        enabled: true #表示启动数据源监控

  #redis配置
  redis:
    port: 6390
    host: 47.107.49.181
    password:

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*/*Mapper.xml
  global-config:

    #数据库主键id自增
    db-config:
      id-type: auto

#dubbo配置
dubbo:
  application:
    name: his-statistics-service
  registry:
    address: zookeeper://47.107.49.181:2181
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: com.qidaiai.service.impl


